---
layout: post
title:  null
date:   2018-08-07 17:59:35 +0800
categories: jekyll update
author: Tom
---

-----------------------------
__目录__
- jekyll 的 kmarkdown 负责解析
{:toc}

-----------------------------
<br>

## java.long.Throwable

> 原文：https://docs.oracle.com/javase/8/docs/api/java/lang/Throwable.html

- 父类：java.lang.Object
- 已实现的接口：Serializable
- 已知直接子类：Error, Exception

在 Java 语言中 Throwable 是所有 Error 和 Exception 的父类。只有此类(或其子类)的实例化对象才能被 Java Virtual Machine 或者 throw 语句抛出。换句话说，只有本类或者本类的子类才能作为 catch 语句的参数。为了编译时检查异常的目的，Throwable 和任何 Throwable 的子类(该子类不同时继承 RuntimeException 和 Error )都被视为检查的异常。

Error 和 Exception 子类的实例化对象通常表示已经出现的异常情况。通常其子类的实例化对象在异常发生的时候被实例化，以便于包含相应的信息(例如调用栈数据)。

一个 Throwable 包含一个线程从它被创建时候开始的堆快照。它也可以再携带一个 String (包含给定的错误信息)。随着时间推移，Throwable 可以抑制其他的 Throwables 的传播。最终，Throwable 也包含一个原因：另外的 Throwable 由于这个 Throwable 而被创建。这一因果关系信息的记录简称为*链式异常* 设施，由于每个异常可能由另一个异常而出发以此类推，导致异常的“链”通常由一个异常引起。

抛出异常的一个原因是抛出它的类是在较低的抽象层次上构建的，由于较低等次的失败导致了更高层次的失败。让较低层次的抽象结构向外抛出异常是较差的设计，因为这样抛出的异常通常与高层次的抽象结构无关。进一步讲，假设较低层次结构的异常被检查到，会将高层次的 API 与低层次的实现细节联系起来。抛出一个“包装异常”(包含了原因的异常)允许高层向其调用者传达失败细节，者可避免上述缺点。它保持了修改上层实现的灵活性而无需修改API(特别是通过方法抛出异常。)。

抛出异常的另一个原因：抛出异常的方法必须符合一般用途接口，不允许方法在未经许可的情况下直接抛出异常。例如， 一个持久性集合符合 `Collection` 接口，并且它实现了 `java.io.Suppose` 那么其内部方法 **add** 可以抛出 `IOException`。这种实现方式，通过将IOException包装在适当的未经检查的异常中，实现可以将IOException的详细信息传递给其调用者，同时符合Collection接口。(持久性集合的规范应该表明其能够抛出的异常)。

一个原因和一个 throwable 能发生两种关联：通过构造方法将原因作为 Throwable 的一个属性，或者通过 `initCause(Throwable)` 方法。希望和原因相关的 throwable 应该提供一个构造方法(该构造方法)可以获取原因(或许是间接的)并且和一个有原因的构造方法相关联。因为 `initCause` 是 `public` 的，该方法允许一个原因与任何 throwable 相关联，甚至一个 “legacy throwable”它的实现早于向Throwable添加异常链机制。

作为惯例，Throwable 和它的子类有两个构造方法，一个无参构造方法，一个接收一个 String 参数(该参数用以记录消息细节)。进而，和它有相关原因的子类应该有两个构造方法，一个以 Throwable(原因)作为参数，另一个以一个 String(详细信息) 和一个 Throwable(原因)作为参数。


## java.lang.Exception

> 原文：https://docs.oracle.com/javase/8/docs/api/java/lang/Exception.html

- 继承关系
    ```
    java.lang.Object
       java.lang.Throwable
           java.lang.Exception 
    ```
- 已实现的接口：Serializable

Exception 类和其子类是可抛出的形式。指示合理应用程序可能希望捕获的条件。

Exception 类和其子类(不包含 RuntimeException)是*检查型异常*。如果它们能在运行时被方法或者构造方法抛出并且在方法外传播，则需要在方法或者构造方法的 throws 关键字后声明异常类型。

## java.lang.RuntimeException

> 原文：https://docs.oracle.com/javase/8/docs/api/java/lang/RuntimeException.html

- 继承关系
    ```
     java.lang.Object
        java.lang.Throwable
            java.lang.Exception
                java.lang.RuntimeException 
    ```
- 实现的接口：Serializable

RuntimeException 是 Exception 的子类，它可以在 Java Virtual Machine 正常运行期间被抛出。

RuntimeException 和它的子类是 *(编译时)不被检查的异常* 。如果在方法或构造函数的执行中抛出并在方法或构造函数边界之外传播，则不需要在方法或构造函数的抛出子句中声明未检查的异常。